[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
eth_sepolia = "${ETH_SEPOLIA_RPC_URL}"
arb_sepolia = "${ARB_SEPOLIA_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
